# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049ee0b67d0fe7a90d2c605ef415b03eb0f52a53d512efed261d71409ea150f5bb57481cdbed62cab7d201f9390d3b4e25e686d1fbb8615afab54e82e0e81ad4

test:
  secret_key_base: ec8ea7a1df18d272b442d6697985237abb434441c14270c19ad220e4b59b2f432b9fa1284bc16b354737a86cd8112fc03efd5db3b267cccab8827d17b608d4f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
